#+TITLE: CFD pratique

** Sillage en aval d'un cylindre sous *OpenFOAM v8*. Voir les solutions expérimentales dans _cours-M2/introduction_images.pdf/pages 12_.
*** Case set-up:
**** un écoulement de fluide de viscosité $$mu=1$$ arrive avec une vitesse uniforme $$U=1$$ sur un cylindre de diamètre $$D=1$$
*** Résultats en fonctions de Re
**** écoulement stationnaire avec _simpleFoam_
*****
$$Re=1$$ 
N'est pas aussi symétrique que dans l'essai expérimental. 
Pas de tourbillons derrière le cylindre. 
Les vitesses max se trouvent aux deux côtés du cylindre
*****
$$Re=6$$ NB: pour augmenter le nombre de Reynolds, on diminue la valeur de viscosité dans _constant/transportProperties_ 
Résultat très resemblable que Re=1.
****** Remarques sur la [[convergence]]
******* Rq: le calcul s'arrête avec un nombre d'itération plus élevé que Re=1, il a besoin de résoudre plus d'équations pour converger.
******* Rq: en ^^raffinant^^ le maillage, le nombre d'itération augmente. On retrouve les mêmes résultats (Umax=1,7 m/s) que le 1er maillage, donc on peut conclure que pour un cas de calcul aussi simple que celui-ci, le 1er maillage est suffisant à l'égard de la convergence.
*****
$$Re=40$$ Tourbillons à l'arrière du cylindre. 
Rq: il y a plus de tourbillons en bas de la ligne centrale qu'en haut, i.e. perte de symétrie
**** écoulement instationnaire avec _pimpleFoam_. Au bout de 40 secondes, je mesure toutes les 2 secondes mais le calcul se fait toutes les 0,001 secondes.
*****
$$Re=1$$ Le résultat n'a pas sens physique, ça indique que le problèm est mal posé.
On doit savoir que pour une fluide de viscosité de 1, arrive avec une vitesse initiale de 1 sur un cylindre de diamètre =1, le comportement en réalité est stationnaire et laminair, on ne peut pas utiliser le solver instationnaire pour résoudre numériquement!! D'où l'intérêt de consulter les essais expérimentaux avant de lancer un calcul numérique, il faut savoir le sens physique!
*****
$$Re=40$$ 
L'écoulement est instationnaire de 0 jusqu'à t=12, après lequel l'écoulement est stationnaire. Dans le cas instationnaire, on s'intéresse aux oscillations ou aux évolutions.
****** Remarques sur la [[convergence]]:
******* La Umax=1,5 indique que le calcul n'a pas convergé, donc on raffine jusqu'au 2eme maillage. Alors qu'on obtient Umax=1,6 donc on raffine jusqu'au 3eme maillage. Mais Umax reste la même, on peut donc
****
***
