#+TITLE: CFD pratique

** Sillage en aval d'un cylindre sous *OpenFOAM v8*. Voir les solutions expérimentales dans _cours-M2/introduction_images.pdf/pages 12_.
*** Case set-up:
**** un écoulement de fluide de viscosité $$mu=1$$ arrive avec une vitesse uniforme $$U=1$$ sur un cylindre de diamètre $$D=1$$
*** Résultats en fonctions de Re:
**** écoulement stationnaire avec _simpleFoam_:
*****
$$Re=1$$ 
N'est pas aussi symétrique que dans l'essai expérimental. 
Pas de tourbillons derrière le cylindre. 
Les vitesses max se trouvent aux deux côtés du cylindre
*****
$$Re=6$$ NB: pour augmenter le nombre de Reynolds, on diminue la valeur de viscosité dans _constant/transportProperties_ 
Résultat très resemblable que Re=1.
****** Remarques sur la [[convergence]]
******* Rq: le calcul s'arrête avec un nombre d'itération plus élevé que Re=1, il a besoin de résoudre plus d'équations pour converger.
******* Rq: en ^^raffinant^^ le maillage, le nombre d'itération augmente. On retrouve les mêmes résultats (Umax=1,7 m/s) que le 1er maillage, donc on peut conclure que pour un cas de calcul aussi simple que celui-ci, le 1er maillage est suffisant à l'égard de la convergence.
*****
$$Re=40$$ Tourbillons à l'arrière du cylindre. 
Rq: il y a plus de tourbillons en bas de la ligne centrale qu'en haut, i.e. perte de symétrie
****** Remarques sur l'instationnalité avec _simpleFoam_:
******* Ce problème est en réalité instationnaire, mais on constate que les résultats numérique avec le solver stationnaire ont un sens physique. Seulement les tourbillons sont moins nombreux qu'avec solver instationnaire, voir ci-dessous. Donc on peut supposer que l'écoulement est stationnaire en utilisant _simpleFoam_ pour ces cas instationnaires en réalité.
******* DONE On va faire les mêmes comparaisons pour un cas de Re=100.
:PROPERTIES:
:todo: 1610895950312
:done: 1610898788166
:END:
******** Conclusion: les résultats de _simpleFoam_ n'ont pas d'allées tourbillons de von Karman mais ont un détachement tourbillonnaire.
**** écoulement instationnaire avec _pimpleFoam_. Au bout de 40 secondes, je mesure toutes les 2 secondes mais le calcul se fait toutes les 0,001 secondes:
*****
$$Re=1$$ Le résultat n'a pas sens physique, ça indique que le problèm est mal posé.
On doit savoir que pour une fluide de viscosité de 1, arrive avec une vitesse initiale de 1 sur un cylindre de diamètre =1, le comportement en réalité est stationnaire et laminair, on ne peut pas utiliser le solver instationnaire pour résoudre numériquement!! D'où l'intérêt de consulter les essais expérimentaux avant de lancer un calcul numérique, il faut savoir le sens physique! Quand le problème est stationnaire, ça marche pas avec _pimpleFoam_!! (c'est la raison pour laquelle je ne pouvais pas avoir de bons résultats pendant la période de stage!)
*****
$$Re=40$$ 
L'écoulement est instationnaire de 0 jusqu'à t=14, après lequel l'écoulement est stationnaire. Dans le cas instationnaire, on s'intéresse aux oscillations ou aux évolutions.
****** Remarques sur la [[convergence]]:
******* La Umax=1,5 indique que le calcul n'a pas convergé, donc on raffine jusqu'au 2eme maillage. Alors qu'on obtient Umax=1,6 donc on raffine jusqu'au 3eme maillage. Mais Umax reste la même, on pourra étudier les causes ultérieurement, mais on va utiliser une erreur relative de 6% pour dire qu'il a convergé.
****** Remarques sur le [[maillage]]
******* Certes, le 2eme et 3eme maillage ont un temps de calcul très important. Mais ils n'ont pas apporté des résultats très différents. Donc on peut conclure qu'un nombre d'élément = 17000 suffit pour un cas de calcul aussi simple.
******* En raffinant, l'écoulement devient toujours stationnaire en t=14.
*****
$$Re=100$$ On observe un détachement tourbillonnaire et des allées de tourbillons de von Karman
*****
** TP1 - M2 écoulement établi en canal plan
