#+TITLE: cours de Turbulence

** Chap1 Introduction à l'étude des écoulements turbulents
*** Introduction
**** signification du qualificatif "turbulent":
***** irrégulier dans le temps et dans l'espace
***** ^^très sensible aux conditions initiales^^
***** d'apparence aléatoire
***** tridimensionnel
***** rotationnel
***** difficilement prédictibles (ex: météorologie)
**** La turbulence dans les écoulements de fluide est un phénomène encore imparfaitement compris, pour lequel il n’existe pas de théorie complète.
***** On sait que ce phénomène est décrit par les équations de Navier-Stokes et qu’il traduit un comportement particulier des solutions de ces équations.
***** Les propriétés considérées comme génériques n'ont pas été prouvées rigoureusement.
***** Les modèles permettant la prédiction numérique sont plut au moins empiriques, ils utilisent un mode de description statistique.
*** Deux exemples de transition laminaire-turbulent
**** Expérience d’Osborne Reynolds (1842–1912)
***** Le nombre de Reynolds indique une transition entre régime laminaire et turbulent. Rq: _Re_ dépend du niveau de perturbation, e.g.  le critère courant pour le calcul des pertes de charge en tuyau: _Re=2000_
****** e.g. Un écoulement de fluide de viscosité ν arrive avec une vitesse unforme U∞x sur un cylindre de diamètre D = 2R, d’axe (O, z) normal à x. Le nombre de Reynolds est défini par
R e =U∞D/ν
***** Malgré la simplicité de sa géométrie, l’écoulement de Poiseuille est en fait très complexe. Tous les écoulements ne présentent pas ce caractère.
**** Sillage derrière un cylindre
***** Des observations expérimentales ont été représentées dans le cours, j'essaie de faire des calculs numériques dans [[CFD pratique]] pour retrouver les résultats.
***** détachement tourbillonnaire (vortex shedding)
****** it takes place when a fluid flows past a bluff body (opposed to streamlined body)
****** it is related to the Strouhal number
***** allées de tourbillons de von Karman (vortex street)
****** observées souvent dans une conduite, derrière un obstacle
****** 阻流体下游的两侧，会产生两道非对称地排列的旋涡，其中一侧的旋涡循时针方向转动，另一旋涡则反方向旋转，这两排旋涡相互交错排列，各个旋涡和对面两个旋涡的中间点对齐，如街道道两边的街灯一般，故名涡街。
*** Turbulence et stabilité des écoulements. Une solution exacte d'une équation du mouvement ne peut être observée si elle n'est pas stable ou établie.
**** l’écoulement turbulent qui s’établit possède les mêmes symétries que l’écoulement laminaire.
**** DONE question: quand on dit un écoulement stabilise, c'est qu'il converge?
:PROPERTIES:
:todo: 1610959229599
:done: 1610996639129
:END:
***** NON, rien à voir avec la convergence! écoulement stable ou établi a une forme asymptotique. c'est ce qu'on observe dans un canal rectiligne après une certante longueur de parcours.
**** Propriété de stabilité
***** problèmes non dissipatifs : équations d’Euler
****** on néglige la viscosité donc la dissipation epsilon = 0
*** Le nombre de Reynolds
**** terme de dissipation est  nécessairement négatif (ou nul). La viscosité a ainsi pour effet de dissiper l’énergie cinétique en chaleur (énergie interne).
*** La turbulence apparaît comme un mouvement du fluide aux multiples échelles caractéristiques.
Ce sont les termes non linéaires des équations de Navier-Stokes qui sont responsables de la création de nombreuses échelles
**** lié avec la longeur d'onde
*** Un écoulement turbulent décrit uniquement par ses grandeurs physiques moyennes a une apparence beaucoup plus simple que ses réalisations particulières
