#+TITLE: cours de Turbulence

** Chap1 Introduction à l'étude des écoulements turbulents
*** Introduction
**** signification du qualificatif "turbulent":
***** irrégulier dans le temps et dans l'espace
***** ^^très sensible aux conditions initiales^^
***** d'apparence aléatoire
***** tridimensionnel
***** rotationnel
***** difficilement prédictibles (ex: météorologie)
**** La turbulence dans les écoulements de fluide est un phénomène encore imparfaitement compris, pour lequel il n’existe pas de théorie complète.
***** On sait que ce phénomène est décrit par les équations de Navier-Stokes et qu’il traduit un comportement particulier des solutions de ces équations.
***** Les propriétés considérées comme génériques n'ont pas été prouvées rigoureusement.
***** Les modèles permettant la prédiction numérique sont plut au moins empiriques, ils utilisent un mode de description statistique.
*** Deux exemples de transition laminaire-turbulent
**** Expérience d’Osborne Reynolds (1842–1912)
***** Le nombre de Reynolds indique une transition entre régime laminaire et turbulent. Rq: _Re_ dépend du niveau de perturbation, e.g.  le critère courant pour le calcul des pertes de charge en tuyau: _Re=2000_
****** e.g. Un écoulement de fluide de viscosité ν arrive avec une vitesse unforme U∞x sur un cylindre de diamètre D = 2R, d’axe (O, z) normal à x. Le nombre de Reynolds est défini par
R e =U∞D/ν
***** Malgré la simplicité de sa géométrie, l’écoulement de Poiseuille est en fait très complexe. Tous les écoulements ne présentent pas ce caractère.
**** Sillage derrière un cylindre
***** Des observations expérimentales ont été représentées dans le cours, j'essaie de faire des calculs numériques dans [[CFD pratique]] pour retrouver les résultats.
***** détachement tourbillonnaire (vortex shedding)
****** it takes place when a fluid flows past a bluff body (opposed to streamlined body)
****** it is related to the Strouhal number
***** allées de tourbillons de von Karman (vortex street)
****** observées souvent dans un système tourbillons
