#+TITLE: thèse

** à la recherche d'une proposition de thèse, je collecte également les [[outils de recherche]] qui vons me servir
** le rendez-vous du 14/01/2021 avec M.Escriva sur le sujet d'exchangeur thermique:
*** Questions à poser:
**** DONE 1. sur quelle [[type d'échangeur]]?
:PROPERTIES:
:later: 1610644527844
:done: 1610644525821
:END:
**** DONE  2. on va effectuer des essais expérimentaux ? par exemple pour déterminer le [[coefficient de transfert]] ou de [[convection]]
:PROPERTIES:
:done: 1610645040166
:END:
**** DONE  3. l'objectif de la thèse?
:PROPERTIES:
:done: 1610645516419
:END:
*** Conclusion:
**** c'est M.Cressel qui envisage de proposer une thèse sur l'échangeur à spirale (à confirmer...), alors que M.Escriva serait le co-encadrant notamment pour OpenFOAM.
**** On pourrait faire des essais expérimentaux pour la validation.
**** Le sujet est encore en phase de préparation, le financement n'est pas ok encore. Continuer à chercher les thèse cifre et autres.
***** TODO CSC date limite pour soumettre une proposition?
**** le prochaine rdv aura lieu autour du 21/01/2021 à l'école Centrale à Ecully.
